"""Final Spawn Revision

Revision ID: 89afe6be0d88
Revises: 3bf56112df9b
Create Date: 2025-06-09 13:58:05.558530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89afe6be0d88'
down_revision: Union[str, None] = '3bf56112df9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('spawn_proposals_spawn_id_fkey', 'spawn_proposals', type_='foreignkey')
    op.drop_column('spawn_proposals', 'spawn_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spawn_proposals', sa.Column('spawn_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('spawn_proposals_spawn_id_fkey', 'spawn_proposals', 'spawns', ['spawn_id'], ['id'])
    # ### end Alembic commands ###
