"""Character Validation Changes

Revision ID: a8f65d8ccb2f
Revises: 42646cafeeba
Create Date: 2025-05-24 13:49:12.416349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f65d8ccb2f'
down_revision: Union[str, None] = '42646cafeeba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('level', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('vocation', sa.String(length=50), nullable=False))
    op.add_column('characters', sa.Column('validation_hash', sa.String(length=120), nullable=True))
    op.alter_column('characters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('characters_verification_id_key', 'characters', type_='unique')
    op.create_unique_constraint(None, 'characters', ['validation_hash'])
    op.drop_column('characters', 'verified')
    op.drop_column('characters', 'verification_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('verification_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'characters', type_='unique')
    op.create_unique_constraint('characters_verification_id_key', 'characters', ['verification_id'])
    op.alter_column('characters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('characters', 'validation_hash')
    op.drop_column('characters', 'vocation')
    op.drop_column('characters', 'level')
    # ### end Alembic commands ###
