"""Assign Points to user

Revision ID: d42b77f07ca4
Revises: a76c147d7d0c
Create Date: 2025-06-30 16:36:50.134794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42b77f07ca4'
down_revision: Union[str, None] = 'a76c147d7d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('_character_spawn_points_uc', 'points', type_='unique')
    op.create_unique_constraint('_character_spawn_points_uc', 'points', ['user_id', 'spawn_id'])
    op.drop_constraint('points_character_id_fkey', 'points', type_='foreignkey')
    op.create_foreign_key(None, 'points', 'users', ['user_id'], ['id'])
    op.drop_column('points', 'character_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'points', type_='foreignkey')
    op.create_foreign_key('points_character_id_fkey', 'points', 'characters', ['character_id'], ['id'])
    op.drop_constraint('_character_spawn_points_uc', 'points', type_='unique')
    op.create_unique_constraint('_character_spawn_points_uc', 'points', ['character_id', 'spawn_id'])
    op.drop_column('points', 'user_id')
    # ### end Alembic commands ###
