"""fix(Bid): remove fields scheduled_start, is_locked, change claim_time from Integer to Interval

Revision ID: df816a3af20e
Revises: f9a09944bf77
Create Date: 2025-07-01 16:16:56.745555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df816a3af20e'
down_revision: Union[str, None] = 'f9a09944bf77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bids', 'claim_time',
               existing_type=sa.INTEGER(),
               type_=sa.Interval(),
               existing_nullable=False,
               postgresql_using='claim_time::int * interval \'1 minute\'') # Or 'claim_time::int * \'1 minute\'::interval')
    op.drop_column('bids', 'is_locked')
    op.drop_column('bids', 'scheduled_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('scheduled_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('bids', sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('bids', 'claim_time',
               existing_type=sa.Interval(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
