"""add timeslots

Revision ID: f346eec4c799
Revises: df816a3af20e
Create Date: 2025-07-08 15:27:24.012932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f346eec4c799'
down_revision: Union[str, None] = 'df816a3af20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeslots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spawn_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('points_paid', sa.Integer(), nullable=True),
    sa.Column('bid_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['spawn_id'], ['spawns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hunts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('hunts_character_id_fkey', 'hunts', type_='foreignkey')
    op.create_foreign_key(None, 'hunts', 'users', ['user_id'], ['id'])
    op.drop_column('hunts', 'character_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hunts', sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'hunts', type_='foreignkey')
    op.create_foreign_key('hunts_character_id_fkey', 'hunts', 'characters', ['character_id'], ['id'])
    op.drop_column('hunts', 'user_id')
    op.drop_table('timeslots')
    # ### end Alembic commands ###
