"""fix(Bid): assign bids to user

Revision ID: f9a09944bf77
Revises: d42b77f07ca4
Create Date: 2025-07-01 16:08:37.234297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9a09944bf77'
down_revision: Union[str, None] = 'd42b77f07ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('_character_spawn_start_uc', 'bids', type_='unique')
    op.drop_constraint('bids_character_id_fkey', 'bids', type_='foreignkey')
    op.create_foreign_key(None, 'bids', 'users', ['user_id'], ['id'])
    op.drop_column('bids', 'character_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bids', type_='foreignkey')
    op.create_foreign_key('bids_character_id_fkey', 'bids', 'characters', ['character_id'], ['id'])
    op.create_unique_constraint('_character_spawn_start_uc', 'bids', ['character_id', 'spawn_id', 'hunt_window_start'])
    op.drop_column('bids', 'user_id')
    # ### end Alembic commands ###
