"""wipe schedule data, add status to bids

Revision ID: fc2bdb4668e3
Revises: 56c91081eb68
Create Date: 2025-07-16 15:50:13.470302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2bdb4668e3'
down_revision: Union[str, None] = '56c91081eb68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade():
    # Create the enum type first
    bidstatus = sa.Enum('PENDING', 'SUCCESSFUL', 'FAILED', name='bidstatus')
    bidstatus.create(op.get_bind())

    """Wipe Data. """
    op.execute("TRUNCATE TABLE bids, hunts, timeslots RESTART IDENTITY CASCADE;")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('status', sa.Enum('PENDING', 'SUCCESSFUL', 'FAILED', name='bidstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bids', 'status')
    # ### end Alembic commands ###
    # Then drop the enum type
    bidstatus = sa.Enum('PENDING', 'SUCCESSFUL', 'FAILED', name='bidstatus')
    bidstatus.drop(op.get_bind())
