version: "3.8"
services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_dat:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports: # Corrected ports section
      - "${DB_PORT}:5432" # Ensure both host and container ports are specified
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - PYTHONPATH=/app
    volumes:
      - ./app:/app # Changed from /huntmaster to /app
    working_dir: /app # Explicitly set working directory
    command: sh -c "ls -la /app && uvicorn main:app --host 0.0.0.0 --port 8000"
volumes:
  postgres_dat: # Define the volume here
